sudo: false
language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

addons:
  postgresql: 9.6

env:
  - TOXENV=py2.7-django1.8-postgresql
  - TOXENV=py3.3-django1.8-postgresql
  - TOXENV=py3.4-django1.8-postgresql
  - TOXENV=py2.7-django1.11-postgresql
  - TOXENV=py3.4-django1.11-postgresql
  - TOXENV=py3.5-django1.11-postgresql
  - TOXENV=py3.6-django1.11-postgresql
  - TOXENV=py3.4-django2.0-postgresql
  - TOXENV=py3.5-django2.0-postgresql
  - TOXENV=py3.6-django2.0-postgresql

install: pip install tox coveralls

before_script:
  - psql -c 'CREATE USER tree SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE tree OWNER tree;' -U postgres

script: tox -e $TOXENV

after_success: coveralls
