sudo: false
language: python

python: 3.6

# work-around for https://github.com/travis-ci/travis-ci/issues/4794
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.3
      - python3.5

addons:
  postgresql: 9.6

env:
  - TOXENV=py2.7-django1.8-postgresql
  - TOXENV=py3.3-django1.8-postgresql
  - TOXENV=py3.4-django1.8-postgresql
  - TOXENV=py2.7-django1.11-postgresql
  - TOXENV=py3.4-django1.11-postgresql
  - TOXENV=py3.5-django1.11-postgresql
  - TOXENV=py3.6-django1.11-postgresql
  - TOXENV=py3.4-django2.0-postgresql
  - TOXENV=py3.5-django2.0-postgresql
  - TOXENV=py3.6-django2.0-postgresql



sudo: false

install: pip install tox coveralls

before_script:
  - psql -c 'CREATE USER tree SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE tree OWNER tree;' -U postgres

script: tox -e $TOXENV

after_success: coveralls
