sudo: false
language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

addons:
  postgresql: 9.6

install: pip install tox coveralls

before_script:
  - psql -c 'CREATE USER tree SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE tree OWNER tree;' -U postgres

script: tox -v

after_success: coveralls
