# Generated by Django 5.2.6 on 2026-06-28 23:51

import django.db.models.deletion
import tree.fields
import tree.models
import uuid
from django.db import migrations, models

from tree.operations import CreateTreeTrigger


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tree', '0003_tree_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescendingPlace',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('path', tree.fields.PathField(order_by=['-name'])),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tests.descendingplace',
                    ),
                ),
            ],
            options={
                'ordering': ['path'],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MultiPathPlace',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                (
                    'name_path',
                    tree.fields.PathField(
                        order_by=['name'], parent_field_name='name_parent'
                    ),
                ),
                (
                    'code_path',
                    tree.fields.PathField(
                        order_by=['code'], parent_field_name='code_parent'
                    ),
                ),
                (
                    'code_parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='code_children',
                        to='tests.multipathplace',
                    ),
                ),
                (
                    'name_parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='name_children',
                        to='tests.multipathplace',
                    ),
                ),
            ],
            options={
                'ordering': ['name_path'],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProtectPlace',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('path', tree.fields.PathField(order_by=['name'])),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='tests.protectplace',
                    ),
                ),
            ],
            options={
                'ordering': ['path'],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SetNullPlace',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('path', tree.fields.PathField(order_by=['name'])),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='tests.setnullplace',
                    ),
                ),
            ],
            options={
                'ordering': ['path'],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UUIDPlace',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('path', tree.fields.PathField(order_by=['name'])),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tests.uuidplace',
                    ),
                ),
            ],
            options={
                'ordering': ['path'],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WeirdTableNamePlace',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('path', tree.fields.PathField(order_by=['name'])),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tests.weirdtablenameplace',
                    ),
                ),
            ],
            options={
                'db_table': 'Tree Weird Table',
                'ordering': ['path'],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('century', models.SmallIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                (
                    'path',
                    tree.fields.PathField(
                        order_by=['century', 'last_name', 'first_name']
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tests.person',
                    ),
                ),
            ],
            options={
                'ordering': ['path'],
                'indexes': [
                    models.Index(
                        models.F('path__level'),
                        models.F('path'),
                        name='person_path_level_index',
                    )
                ],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('path', tree.fields.PathField(order_by=['name'])),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tests.place',
                    ),
                ),
            ],
            options={
                'ordering': ['path', 'name'],
                'indexes': [
                    models.Index(
                        models.F('path__level'),
                        models.F('path'),
                        name='place_path_level_index',
                    )
                ],
            },
            bases=(tree.models.TreeModelMixin, models.Model),
        ),
        # The tree triggers are created once all tables and columns exist.
        # `WeirdTableNamePlace` is intentionally left without one:
        # `UnusualTableNameTest` installs it at runtime.
        CreateTreeTrigger('tests.DescendingPlace'),
        CreateTreeTrigger('tests.MultiPathPlace', 'name_path'),
        CreateTreeTrigger('tests.MultiPathPlace', 'code_path'),
        CreateTreeTrigger('tests.ProtectPlace'),
        CreateTreeTrigger('tests.SetNullPlace'),
        CreateTreeTrigger('tests.UUIDPlace'),
        CreateTreeTrigger('tests.Person'),
        CreateTreeTrigger('tests.Place'),
    ]
