# Generated by Django 5.2.6 on 2026-06-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0003_test_migrations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_length_index',
        ),
        migrations.AlterField(
            model_name='person',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tests.person',
            ),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tests.place',
            ),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(models.F('path__level'), name='person_path_level_index'),
        ),
    ]
