# Generated by Django 5.2.6 on 2026-06-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0005_tree_test_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_parent_index',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_slice_1_index',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_slice_2_index',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_slice_3_index',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_slice_4_index',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_slice_5_index',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_path_level_index',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_path_parent_index',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_path_level_index',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_path_slice_1_index',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_path_slice_2_index',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_path_slice_3_index',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_path_slice_4_index',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_path_slice_5_index',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(
                models.F('path__level'),
                models.F('path'),
                name='person_path_level_index',
            ),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(
                models.F('path__level'), models.F('path'), name='place_path_level_index'
            ),
        ),
    ]
